# Generated by Django 2.2.16 on 2021-09-08 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210907_1614'),
        ('users', '0002_auto_20210908_1616'),
    ]

    operations = [
    ]
